### ISSUE TITLE
Does not build on 9.6

### ISSUE THREAD

**Issue by emberdart** [CLowcay/hs-gedcom#6]
Hi,

I'm getting the following issue attempting to build on ghc 9.6:

```
 [4 of 9] Compiling Data.Gedcom.Internal.ParseMonads ( src/Data/Gedcom/Internal/ParseMonads.hs, dist/build/Data/Gedcom/Internal/ParseMonads.o, dist/build/Data/Gedcom/Internal/ParseMonads.dyn_o )
>
> src/Data/Gedcom/Internal/ParseMonads.hs:29:69: error:
>     Module ‘Control.Monad.Except’ does not export ‘MonadTrans’
>    |
> 29 | import Control.Monad.Except (ExceptT (..), MonadError (throwError), MonadTrans (lift), runExceptT)
```

It builds fine on 9.4 however.

Can this be addressed please?

Thanks
